title: Thank you for visiting TyataEssence blog - a space where complexity meets clarity!
author: Rakesh Tyata
email: tyataessence@gmail.com
description: "This blog is about sharing ideas — it’s about creating a place where readers can slow down, think clearly, and discover meaningful perspectives in a fast-moving world."
baseurl: ""
url: "https://tyataessence.github.io"

# Sidebar settings
show_sidebar: true

sidebar:
  author:
    name: "Rakesh Tyata"
    bio: "Blogger | Developer | Thinker"
    desc: 
      - "Simplifying complex ideas across tech, personal insights, and trending topics."
      - "Sharing practical tutorials and personal reflections."
      - "Highlighting emerging trends in technology and society."
      - "Taking control of your own happiness, despite life's unfairness."
    image: "/assets/images/profile_pic.jpg"  
    email: "tyataessence@gmail.com"
    address: "Seattle, WA, USA"
    links:
      Portfolio: "https://rtyata01.github.io/"
      Youtube: "https://www.youtube.com/@TyataEssence"
  
  categories:
    - Insights
    - Personal
    - Technical
    - Trending

# Add this instead:
remote_theme: mmistakes/minimal-mistakes@4.27.3

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Use custom homepage layout for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"

